# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
title: VLAB
email: vlabsys@gmail.com
description: Experiment System
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: 
repository_url: https://github.com/vlabsys

# Language and Timezone
lang: # the language of your site, "en" (default, English), "zh"(简体中文), "zh-Hans"(简体中文), "zh-Hant"(繁體中文)
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


# Author
author:
  type      : organization # "person" (default), "organization"
  name      : VLAB
  url       : https://github.com/vlabsys
  email     : vlabsys@gmail.com
  github    : VLabSys # "user_name" the last part of your profile url, e.g. https://github.com/user_name



## => Paths

##############################

paths:

  root    : # title link url, "/" (default)

  home    : # home layout url, "/" (default)

  archive : # "/archive.html" (default)

  rss     : # "/feed.xml" (default)

  ## => Markdown Enhancements

##############################

## Mathjax

mathjax: # false (default), true

mathjax_autoNumber: # false (default), true



## Mermaid

mermaid: # false (default), true



## Chart

chart: # false (default), true



## => Paginate

##############################

paginate: 8

paginate_path: /page:num # don't change this unless for special need


defaults:
  - scope:
      path: docs
    values:
      layout: article
      sidebar:
        nav: docs
      aside:
        toc: true
      show_edit_on_github: true

# Build settings
incremental: true
livereload: true
markdown: kramdown
highlighter : rouge
permalink   : date
#theme: jekyll-text-theme
remote_theme: kitian616/jekyll-text-theme 
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
